### ISSUE TITLE
lmod_cache monitoring needs initialized file

### ISSUE THREAD

**Issue by kwaegema** [hpcugent/Lmod-UGent#24]
The lmod_cache check will fail when not run as root, since it tries to write and chown a file under /var/cache. Workaround:
```
touch /var/cache/run_lmod_cache.nagios.json.gz
chown vsc40003:nrpe /var/cache/run_lmod_cache.nagios.json.gz
```

The script should check the existance of this file and give a clear error message if this is missing

**Comment by wpoely86** [comment]
@kwaegema it runs as a vsc user.
