### ISSUE TITLE
provide /usr/bin/modulecmd if possible

### ISSUE THREAD

**Issue by stdweird** [hpcugent/Lmod-UGent#46]
is it possible to ship a (small) wrapper `/usr/bin/modulecmd` that is either compatible with env-modules? not sure what it entails

**Comment by stdweird** [comment]
@boegel i need this to resolve some rpm dependencies, but i'm clueless if it is feasible at all

**Comment by boegel** [comment]
Can you clarify the need for this?

A simple wrapper around the `lmod` binary should be sufficient, but of course it's not going to be full compatible with the real `modulecmd` (which doesn't know about Lua, doesn't support options that Lmod supports, etc.).

**Comment by stdweird** [comment]
the `scl-utils` rpm requires `/usr/bin/modulecmd` (currently only provided by the `env-modules` rpm, which conflicts with Lmod), not sure to what extend compatibility is required.
